const fs = require('fs-extra')

fs.ensureDirSync('./Dir1')
fs.ensureFileSync('./Dir1/File1.txt')
fs.ensureDirSync('./Dir2')
fs.moveSync('./Dir1/File1.txt', './Dir2/File1.txt')
fs.ensureDirSync('./Dir3')
fs.copySync('./Dir2/File1.txt', './Dir3/File1.txt')
fs.writeJsonSync('./Dir1/FileWithName.json', {name: "Pavel"})
const data = fs.readJSONSync('./Dir1/FileWithName.json')
console.log(data.name)
fs.removeSync('./Dir1/FileWithName.json')
fs.removeSync('./Dir2/File1.txt')
fs.removeSync('./Dir3/File1.txt')
fs.removeSync('./Dir1')
fs.removeSync('./Dir2')
fs.removeSync('./Dir3')